/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
}
rootProject.name = "SciBot"
include("SciBot", "SciBot-dependencies")
